import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resetControllersBuild, resolvePaths, writeIfChanged } from "./controllers.js";
import { enumerateControllers, resetEnumeration, typeNames } from "./meta.js";

/**
 * JSDoc typedef module (doc 02 section 5.3, decision 66).
 *
 * `src/theme/controllers/types.js` holds only `@typedef` comments and `export {};`. It is copied
 * verbatim to `contract/controllers.types.js`, then a generated block is appended:
 *
 *   - the `@template` typedefs `Controller`, `ControllerHost` (taken from the controller core of this kit,
 *     so they cannot drift) and `ApiResult`, inlined, because the file imports nothing;
 *   - a fallback `<Name>State` / `<Name>Actions` from the enumerated keys for each controller lacking them;
 *   - `@typedef {{ 'market/cart': Controller<CartState, CartActions>, ... }} Controllers`.
 *
 * No `types.js` = fallbacks only.
 */

const CORE_FILE = fileURLToPath(new URL("../controller/index.js", import.meta.url));

export const GENERATED_MARKER =
  "// ---- generated by @panomc/plugin-kit, do not edit below this line ----";

const API_RESULT = `/**
 * What \`host.request\` resolves, and what an action returns when it can fail: the parsed body, or the error envelope.
 * @template [T=object]
 * @typedef {T | { error: { code: string, message?: string, details?: object, fields?: Record<string, string> } }} ApiResult
 */`;

/**
 * Replaces every comment by blanks (newlines kept) so what is left is code.
 *
 * @param {string} text
 * @returns {string}
 */
function blankComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, (comment) => comment.replace(/[^\n]/g, " "));
}

/**
 * Checks that a types.js holds nothing but comments and `export {}`.
 *
 * @param {string} text file content
 * @param {string} [file] shown in the error
 * @throws {Error} naming the first statement and its line
 */
export function validateTypesSource(text, file = "src/theme/controllers/types.js") {
  const code = blankComments(text);
  const leftover = code.replace(/^\s*export\s*\{\s*\}\s*;?[ \t]*$/gm, (match) => match.replace(/[^\n]/g, " "));
  const match = /\S/.exec(leftover);

  if (!match) return;

  const line = leftover.slice(0, match.index).split("\n").length;
  const snippet = leftover.split("\n")[line - 1].trim().slice(0, 60);

  throw new Error(
    `[pano-plugin] ${file}:${line} has code (${snippet}) — types.js may hold only @typedef comments and export {}; move the code to a controller or a view helper`,
  );
}

/**
 * Names declared by `@typedef` / `@callback` comments.
 *
 * @param {string} text
 * @returns {Set<string>}
 */
export function declaredTypeNames(text) {
  const names = new Set();
  const pattern = /@(?:typedef|callback)\b/g;
  let match;

  while ((match = pattern.exec(text))) {
    let index = match.index + match[0].length;

    while (/\s|\*/.test(text[index] ?? "")) index += 1;

    if (text[index] === "{") {
      let depth = 0;

      for (; index < text.length; index += 1) {
        if (text[index] === "{") depth += 1;
        else if (text[index] === "}") {
          depth -= 1;

          if (depth === 0) {
            index += 1;
            break;
          }
        }
      }

      while (/\s|\*/.test(text[index] ?? "")) index += 1;
    }

    const name = /^[A-Za-z_$][\w$]*/.exec(text.slice(index));

    if (name) names.add(name[0]);
  }

  return names;
}

/**
 * @param {string} key
 * @returns {string}
 */
function property(key) {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

/**
 * @param {string[]} members already formatted `key: type` members
 * @returns {string}
 */
function objectType(members) {
  return members.length === 0 ? "{}" : `{ ${members.join(", ")} }`;
}

/**
 * The typedef comments of the controller core that the generated block inlines.
 *
 * @returns {string[]} comment blocks: Controller, ControllerHost
 */
function coreTypedefs() {
  const source = fs.readFileSync(CORE_FILE, "utf8");
  const blocks = source.match(/\/\*\*[\s\S]*?\*\//g) ?? [];
  const wanted = ["Controller", "ControllerHost"];

  return wanted.map((name) => {
    const block = blocks.find((item) => new RegExp(`@typedef \\{Object\\} ${name}\\s`).test(item));

    if (!block) {
      throw new Error(`[pano-plugin] the controller core has no @typedef ${name}; the kit is damaged, reinstall @panomc/plugin-kit`);
    }

    return block;
  });
}

/**
 * Builds the content of `contract/controllers.types.js`.
 *
 * @param {{ namespace: string, controllers: Record<string, { state: string[], actions: string[] }>, authored?: string | null }} input
 *   `authored` = content of the author's types.js (already validated), null when there is none
 * @returns {string}
 */
export function buildTypesModule({ namespace, controllers, authored = null }) {
  const names = Object.keys(controllers).sort();
  const known = declaredTypeNames(authored ?? "");
  const hasExport = authored !== null && /^\s*export\s*\{\s*\}\s*;?/m.test(blankComments(authored));
  const parts = [];

  if (authored !== null) parts.push(authored.replace(/\s+$/, "") + "\n");

  const [controllerDef, hostDef] = coreTypedefs();
  const generated = [GENERATED_MARKER, controllerDef, hostDef, API_RESULT];

  for (const name of names) {
    const { state, actions } = typeNames(name);
    const info = controllers[name];

    if (!known.has(state)) {
      generated.push(
        `/**\n * State of ${namespace}/${name}, generated from the keys of its initial state (declare ${state} in types.js to type it).\n * @typedef {${objectType(info.state.map((key) => `${property(key)}: any`))}} ${state}\n */`,
      );
    }

    if (!known.has(actions)) {
      generated.push(
        `/**\n * Actions of ${namespace}/${name}, generated from its action names (declare ${actions} in types.js to type them).\n * @typedef {${objectType(info.actions.map((key) => `${property(key)}: (...args: any[]) => any`))}} ${actions}\n */`,
      );
    }
  }

  const members = names.map((name) => {
    const { state, actions } = typeNames(name);

    return `'${namespace}/${name}': Controller<${state}, ${actions}>`;
  });

  generated.push(
    `/**\n * Every public controller of ${namespace}, by full name.\n * @typedef {${objectType(members)}} Controllers\n */`,
  );

  parts.push(generated.join("\n\n") + "\n");

  if (!hasExport) parts.push("export {};\n");

  return parts.join("\n");
}

/**
 * @typedef {object} TypesOptions
 * @property {string} [root]
 * @property {string} [dir] controllers folder, default `src/theme/controllers`
 * @property {string} [outDir] package folder, default `src/main/resources/plugin-ui`
 * @property {string} [pluginId] needed with `namespace` when this plugin runs without panoMeta
 * @property {string} [namespace]
 */

/**
 * Copies src/theme/controllers/types.js to contract/controllers.types.js (only @typedef comments
 * and `export {}` allowed) and appends the generated block and the fallback typedefs. List it in the
 * same configuration as `panoControllers` and `panoMeta`; it writes in `writeBundle`.
 *
 * @param {TypesOptions} [options]
 * @returns {import('rollup').Plugin}
 */
export function panoTypes(options = {}) {
  const { dir, outDir } = resolvePaths(options);
  const typesFile = path.join(dir, "types.js");

  return {
    name: "pano-types",
    buildStart() {
      resetControllersBuild(options);
      resetEnumeration(/** @type {any} */ (options));

      if (fs.existsSync(typesFile)) this.addWatchFile(typesFile);
    },
    async writeBundle() {
      const output = path.join(outDir, "contract", "controllers.types.js");
      const authoredText = fs.existsSync(typesFile) ? fs.readFileSync(typesFile, "utf8") : null;

      if (authoredText !== null) validateTypesSource(authoredText, path.relative(resolvePaths(options).root, typesFile).split(path.sep).join("/"));

      const enumeration = await enumerateControllers(/** @type {any} */ (options));

      if (Object.keys(enumeration.controllers).length === 0 && authoredText === null) {
        fs.rmSync(output, { force: true });

        return;
      }

      writeIfChanged(
        output,
        buildTypesModule({
          namespace: enumeration.namespace,
          controllers: enumeration.controllers,
          authored: authoredText,
        }),
      );
    },
  };
}
