// Generated by pano-client from openapi.json. Do not edit; run pano-client again.
import { operations } from './operations.js';

/**
 * Create a post.
 * @deprecated
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').CreatePostRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').CreatePostResponse>>}
 */
export const createPost = (client, params) => client.request(operations.createPost, params);

/**
 * DELETE /api/v1/posts/{url}
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { url: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').DeletePostResponse>>}
 */
export const deletePost = (client, params) => client.request(operations.deletePost, params);

/**
 * Download an export.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { kind: 'posts' | 'users' }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetApiV1ExportByKindResponse>>}
 */
export const getApiV1ExportByKind = (client, params) => client.request(operations.getApiV1ExportByKind, params);

/**
 * GET /api/v1/legacy/thing
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: Record<string, any>, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetLegacyThingResponse>>}
 */
export const getLegacyThing = (client, params) => client.request(operations.getLegacyThing, params);

/**
 * One post by its url.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { url: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPostResponse>>}
 */
export const getPost = (client, params) => client.request(operations.getPost, params);

/**
 * List published posts.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { category?: string, page?: number, pageSize?: number }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPostsResponse>>}
 */
export const getPosts = (client, params) => client.request(operations.getPosts, params);

/**
 * POST /api/v1/profile/avatar
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body?: FormData, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').UploadAvatarResponse>>}
 */
export const uploadAvatar = (client, params) => client.request(operations.uploadAvatar, params);
