// Generated by pano-client from openapi.json. Do not edit; run pano-client again.

export const operations = /** @type {const} */ ({
  createPost: { method: 'POST', path: '/api/v1/posts', auth: 'user', mutation: true },
  deletePost: { method: 'DELETE', path: '/api/v1/posts/{url}', auth: 'user', mutation: true },
  getApiV1ExportByKind: { method: 'GET', path: '/api/v1/export/{kind}', auth: 'none', mutation: false },
  getLegacyThing: { method: 'GET', path: '/api/v1/legacy/thing', auth: 'none', mutation: false },
  getPost: { method: 'GET', path: '/api/v1/posts/{url}', auth: 'none', mutation: false },
  getPosts: { method: 'GET', path: '/api/v1/posts', auth: 'none', mutation: false },
  uploadAvatar: { method: 'POST', path: '/api/v1/profile/avatar', auth: 'user', mutation: true }
});
