// Generated by pano-client from openapi.json. Do not edit; run pano-client again.

/**
 * Who wrote a post.
 * @typedef {Object} Author
 * @property {string | null} [avatar] Head image url.
 * @property {number} id
 * @property {string} username
 */

/** @typedef {Author & { extra?: number }} Combined */

/**
 * @typedef {Object} ErrorEnvelope
 * @property {{ code: string, fields?: Record<string, string>, message?: string }} error
 */

/**
 * @typedef {Object} PageInfo
 * @property {number} number
 * @property {number} size
 * @property {number} totalItems
 * @property {number} totalPages
 */

/** @typedef {{ author: Author, body?: string | Author, id: number, image?: string | null, meta?: Record<string, string>, status: 'DRAFT' | 'PUBLISHED', tags?: string[], title: string, 'x-extra'?: boolean }} Post */

/**
 * @typedef {Object} PostInput
 * @property {number} [categoryId]
 * @property {string} [text]
 * @property {string} title
 */

/**
 * @typedef {Object} PostPage
 * @property {Post[]} items
 * @property {PageInfo} page
 */

/** @typedef {'UP' | 'DOWN'} Status */

/** @typedef {Post} CreatePostResponse */

/** @typedef {PostInput} CreatePostRequest */

/** @typedef {void} DeletePostResponse */

/** @typedef {Blob} GetApiV1ExportByKindResponse */

/** @typedef {any} GetLegacyThingResponse */

/** @typedef {Post} GetPostResponse */

/** @typedef {PostPage} GetPostsResponse */

/** @typedef {{ url: string }} UploadAvatarResponse */

export {};
