// Generated by pano-client from openapi.json. Do not edit; run pano-client again.
import { operations } from './operations.js';

/**
 * Starts an e-mail change: stores the new address as pending and mails a confirmation link.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').ChangeEmailRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').ChangeEmailResponse>>}
 */
export const changeEmail = (client, params) => client.request(operations.changeEmail, params);

/**
 * Turns a verified pending sign-in (social login, magic link) into a session.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').CompletePendingAuthRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').CompletePendingAuthResponse>>}
 */
export const completePendingAuth = (client, params) => client.request(operations.completePendingAuth, params);

/**
 * Opens a ticket with its first message.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').CreateTicketRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').CreateTicketResponse>>}
 */
export const createTicket = (client, params) => client.request(operations.createTicket, params);

/**
 * A one-time ticket for opening the website WebSocket.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').CreateWsTicketResponse>>}
 */
export const createWsTicket = (client, params) => client.request(operations.createWsTicket, params);

/**
 * Deletes every notification of the signed-in user.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').DeleteAllNotificationResponse>>}
 */
export const deleteAllNotification = (client, params) => client.request(operations.deleteAllNotification, params);

/**
 * Deletes one notification of the signed-in user; an unknown or foreign id is ignored.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').DeleteNotificationResponse>>}
 */
export const deleteNotification = (client, params) => client.request(operations.deleteNotification, params);

/**
 * Who the signed-in user is: name, e-mail, panel access and permissions.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetCredentialsResponse>>}
 */
export const getCredentials = (client, params) => client.request(operations.getCredentials, params);

/**
 * The CSRF token of the current cookie session (null for a Bearer token).
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetCsrfTokenResponse>>}
 */
export const getCsrfToken = (client, params) => client.request(operations.getCsrfToken, params);

/**
 * The site icon; redirects to the URL with its hash first.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { hash?: string }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetFaviconResponse>>}
 */
export const getFavicon = (client, params) => client.request(operations.getFavicon, params);

/**
 * The settings of the active front-end, defaults filled in.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetFrontendSettingsResponse>>}
 */
export const getFrontendSettings = (client, params) => client.request(operations.getFrontendSettings, params);

/**
 * Where each page Pano links to lives on the site; paths keep their {name} placeholders.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetFrontendUrlsResponse>>}
 */
export const getFrontendUrls = (client, params) => client.request(operations.getFrontendUrls, params);

/**
 * The languages of the site.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetLocalesResponse>>}
 */
export const getLocales = (client, params) => client.request(operations.getLocales, params);

/**
 * Ten older notifications after a given id; marks them read.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetMoreNotificationsResponse>>}
 */
export const getMoreNotifications = (client, params) => client.request(operations.getMoreNotifications, params);

/**
 * The signed-in user's open sessions.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetMySessionsResponse>>}
 */
export const getMySessions = (client, params) => client.request(operations.getMySessions, params);

/**
 * The signed-in user's notifications, newest first; marks the page read.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { page?: number, pageSize?: number }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetNotificationsResponse>>}
 */
export const getNotifications = (client, params) => client.request(operations.getNotifications, params);

/**
 * The OpenAPI 3.1 document of the public core API
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetOpenApiResponse>>}
 */
export const getOpenApi = (client, params) => client.request(operations.getOpenApi, params);

/**
 * The public profile of a user.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { username: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPlayerProfileResponse>>}
 */
export const getPlayerProfile = (client, params) => client.request(operations.getPlayerProfile, params);

/**
 * The OpenAPI 3.1 document of one plugin's public API
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { pluginId: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPluginOpenApiResponse>>}
 */
export const getPluginOpenApi = (client, params) => client.request(operations.getPluginOpenApi, params);

/**
 * The pano-plugin.json of every plugin whose site UI Pano serves.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPluginPackagesResponse>>}
 */
export const getPluginPackages = (client, params) => client.request(operations.getPluginPackages, params);

/**
 * One plugin's texts in one locale, with the admin's edits applied.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { locale: string, pluginId: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPluginTranslationsResponse>>}
 */
export const getPluginTranslations = (client, params) => client.request(operations.getPluginTranslations, params);

/**
 * One file of a plugin's built package (pano-plugin.json, contract, controllers, samples, widgets).
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { pluginId: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPluginUiFileResponse>>}
 */
export const getPluginUiFile = (client, params) => client.request(operations.getPluginUiFile, params);

/**
 * One published post with the posts before and after it by date.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { url: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPostDetailResponse>>}
 */
export const getPostDetail = (client, params) => client.request(operations.getPostDetail, params);

/**
 * A post by id, draft or not, for a person who may use the panel; same body as a published post.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPostPreviewResponse>>}
 */
export const getPostPreview = (client, params) => client.request(operations.getPostPreview, params);

/**
 * A post thumbnail file.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { filename: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPostThumbnailResponse>>}
 */
export const getPostThumbnail = (client, params) => client.request(operations.getPostThumbnail, params);

/**
 * Published posts, newest first, optionally of one category.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { categoryUrl?: string, page?: number, pageSize?: number }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetPostsResponse>>}
 */
export const getPosts = (client, params) => client.request(operations.getPosts, params);

/**
 * The signed-in user's own profile, with the last login date.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetProfileResponse>>}
 */
export const getProfile = (client, params) => client.request(operations.getProfile, params);

/**
 * Redirects (302) to the picture of a user.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { username: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetProfilePictureResponse>>}
 */
export const getProfilePicture = (client, params) => client.request(operations.getProfilePicture, params);

/**
 * The last five notifications and the number of unread ones, for a dropdown.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetQuickNotificationsResponse>>}
 */
export const getQuickNotifications = (client, params) => client.request(operations.getQuickNotifications, params);

/**
 * The text a new user must accept when registering.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetRegisterAgreementResponse>>}
 */
export const getRegisterAgreement = (client, params) => client.request(operations.getRegisterAgreement, params);

/**
 * The accepted game servers of the site, the main one first; never a host, port or key.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetServersResponse>>}
 */
export const getServers = (client, params) => client.request(operations.getServers, params);

/**
 * What a front-end needs to boot: language, site texts, mode, plugins and theme settings.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetSiteInfoResponse>>}
 */
export const getSiteInfo = (client, params) => client.request(operations.getSiteInfo, params);

/**
 * Every public page of the site, core and plugins, for building a sitemap.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { page?: number, pageSize?: number }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetSitemapResponse>>}
 */
export const getSitemap = (client, params) => client.request(operations.getSitemap, params);

/**
 * A file the admin uploaded in the theme settings.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { filename: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetThemeSettingResourceResponse>>}
 */
export const getThemeSettingResource = (client, params) => client.request(operations.getThemeSettingResource, params);

/**
 * One ticket of the signed-in user with its messages.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetTicketResponse>>}
 */
export const getTicket = (client, params) => client.request(operations.getTicket, params);

/**
 * The ticket categories a new ticket can be filed under.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { page?: number, pageSize?: number }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetTicketCategoriesResponse>>}
 */
export const getTicketCategories = (client, params) => client.request(operations.getTicketCategories, params);

/**
 * The messages of a ticket that came after a given message.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, query: { lastMessageId: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetTicketMessagesResponse>>}
 */
export const getTicketMessages = (client, params) => client.request(operations.getTicketMessages, params);

/**
 * The signed-in user's tickets, filtered by page type or category.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { categoryUrl?: string, page?: number, pageSize?: number, pageType?: ('ALL' | 'WAITING_REPLY' | 'CLOSED')[] }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetTicketsResponse>>}
 */
export const getTickets = (client, params) => client.request(operations.getTickets, params);

/**
 * The texts of one locale and type, with the admin's edits applied.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { code: string, type: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetTranslationsResponse>>}
 */
export const getTranslations = (client, params) => client.request(operations.getTranslations, params);

/**
 * The site logo; redirects to the URL with its hash first.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: { hash?: string }, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetWebsiteLogoResponse>>}
 */
export const getWebsiteLogo = (client, params) => client.request(operations.getWebsiteLogo, params);

/**
 * GET /api/v1/widgets/index.json
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: Record<string, any>, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetWidgetIndexResponse>>}
 */
export const getWidgetIndex = (client, params) => client.request(operations.getWidgetIndex, params);

/**
 * GET /api/v1/widgets/loader.js
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: Record<string, any>, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetWidgetLoaderResponse>>}
 */
export const getWidgetLoader = (client, params) => client.request(operations.getWidgetLoader, params);

/**
 * GET /api/v1/widgets/runtime/*
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: Record<string, any>, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').GetWidgetRuntimeFileResponse>>}
 */
export const getWidgetRuntimeFile = (client, params) => client.request(operations.getWidgetRuntimeFile, params);

/**
 * GET /api/v1/health
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: Record<string, any>, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').HealthResponse>>}
 */
export const health = (client, params) => client.request(operations.health, params);

/**
 * The home page sidebar: server address, main server status and the newest members.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').HomeSidebarResponse>>}
 */
export const homeSidebar = (client, params) => client.request(operations.homeSidebar, params);

/**
 * Signs in with a user name or e-mail and a password.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').LoginRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').LoginResponse>>}
 */
export const login = (client, params) => client.request(operations.login, params);

/**
 * Ends the current session and clears its cookies.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').LogoutResponse>>}
 */
export const logout = (client, params) => client.request(operations.logout, params);

/**
 * Ends one of the signed-in user's sessions; an id that is not theirs is ignored.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').LogoutMySessionResponse>>}
 */
export const logoutMySession = (client, params) => client.request(operations.logoutMySession, params);

/**
 * Marks one notification read; an unknown or foreign id is ignored.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').MarkNotificationAsReadResponse>>}
 */
export const markNotificationAsRead = (client, params) => client.request(operations.markNotificationAsRead, params);

/**
 * Marks the last five notifications read and answers the unread count.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').MarkQuickNotificationsAsReadResponse>>}
 */
export const markQuickNotificationsAsRead = (client, params) => client.request(operations.markQuickNotificationsAsRead, params);

/**
 * The profile page sidebar of a user.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { username: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').PlayerProfileSidebarResponse>>}
 */
export const playerProfileSidebar = (client, params) => client.request(operations.playerProfileSidebar, params);

/**
 * The signed-in user's own profile sidebar.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').ProfileSidebarResponse>>}
 */
export const profileSidebar = (client, params) => client.request(operations.profileSidebar, params);

/**
 * Creates an account; signs the new user in when e-mail verification is not required.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').RegisterRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').RegisterResponse>>}
 */
export const register = (client, params) => client.request(operations.register, params);

/**
 * Sets a new password with the token from the reset mail.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').RenewPasswordRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').RenewPasswordResponse>>}
 */
export const renewPassword = (client, params) => client.request(operations.renewPassword, params);

/**
 * Mails a password reset link to the account of a user name or e-mail.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').ResetPasswordRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').ResetPasswordResponse>>}
 */
export const resetPassword = (client, params) => client.request(operations.resetPassword, params);

/**
 * Mails the signed-in user a password reset link.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').SendResetPasswordEmailResponse>>}
 */
export const sendResetPasswordEmail = (client, params) => client.request(operations.sendResetPasswordEmail, params);

/**
 * Adds a message to an open ticket of the signed-in user.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, body: import('./types.js').SendTicketMessageRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').SendTicketMessageResponse>>}
 */
export const sendTicketMessage = (client, params) => client.request(operations.sendTicketMessage, params);

/**
 * The support page sidebar: the staff members who are online.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').SupportSidebarResponse>>}
 */
export const supportSidebar = (client, params) => client.request(operations.supportSidebar, params);

/**
 * Counts one view of a post; a bot or a repeat view inside the window is not counted.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { url: string }, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').TrackPostViewResponse>>}
 */
export const trackPostView = (client, params) => client.request(operations.trackPostView, params);

/**
 * Changes the signed-in user's language.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').UpdateProfileRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').UpdateProfileResponse>>}
 */
export const updateProfile = (client, params) => client.request(operations.updateProfile, params);

/**
 * Changes the status of a ticket of the signed-in user (closing it).
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ path: { id: number }, body: import('./types.js').UpdateTicketRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').UpdateTicketResponse>>}
 */
export const updateTicket = (client, params) => client.request(operations.updateTicket, params);

/**
 * Confirms an e-mail address with the token from the activation mail.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').VerifyEmailRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').VerifyEmailResponse>>}
 */
export const verifyEmail = (client, params) => client.request(operations.verifyEmail, params);

/**
 * Checks the code a player got in the game; answers a token for finishing the registration.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').VerifyLinkCodeRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').VerifyLinkCodeResponse>>}
 */
export const verifyLinkCode = (client, params) => client.request(operations.verifyLinkCode, params);

/**
 * Confirms a changed e-mail address with the token from the mail.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ body: import('./types.js').VerifyNewEmailRequest, signal?: AbortSignal }} params
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').VerifyNewEmailResponse>>}
 */
export const verifyNewEmail = (client, params) => client.request(operations.verifyNewEmail, params);

/**
 * Counts one visit of the caller's IP address for today.
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').VisitorVisitResponse>>}
 */
export const visitorVisit = (client, params) => client.request(operations.visitorVisit, params);

/**
 * GET /api/v1/ws
 * @param {import('@panomc/client').PanoClient} client
 * @param {{ query?: Record<string, any>, signal?: AbortSignal }} [params]
 * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').WebsiteWebSocketResponse>>}
 */
export const websiteWebSocket = (client, params) => client.request(operations.websiteWebSocket, params);
