// Generated by pano-client from openapi.json. Do not edit; run pano-client again.

/**
 * The body of every non-2xx answer.
 * @typedef {Object} Error
 * @property {{ code: string, details?: Record<string, any>, fields?: Record<string, string>, message?: string }} error
 */

/**
 * @typedef {Object} Locale
 * @property {string} code
 * @property {number} [createdAt]
 * @property {string} dateFnsCode
 * @property {'SYSTEM' | 'USER'} [definedBy]
 * @property {string[]} derivatives
 * @property {number} id
 * @property {string} name
 * @property {number} [updatedAt]
 */

/**
 * @typedef {Object} Notification
 * @property {number} createdAt
 * @property {Record<string, any>} details
 * @property {number} id
 * @property {boolean} isPersonal
 * @property {string | null} pluginId
 * @property {'NOT_READ' | 'READ'} status
 * @property {string} type
 * @property {number} updatedAt
 */

/**
 * Where a list stands: page numbers start at 1, `pageSize` is at most 100.
 * @typedef {Object} Page
 * @property {number} number
 * @property {number} size
 * @property {number} totalItems
 * @property {number} totalPages
 */

/**
 * @typedef {Object} Post
 * @property {{ color?: string, description?: string, id?: number, title: string, url?: string }} category
 * @property {number} date
 * @property {number} id
 * @property {'PUBLISHED' | 'DRAFT' | 'TRASH'} status
 * @property {string} text
 * @property {string} thumbnailUrl
 * @property {string} title
 * @property {string} url
 * @property {number} views
 * @property {{ username: string }} writer
 */

/**
 * @typedef {Object} PostDetail
 * @property {string | { id: number, title: string, url: string }} nextPost
 * @property {Post} post
 * @property {string | { id: number, title: string, url: string }} previousPost
 */

/**
 * @typedef {Object} PostSummary
 * @property {{ color?: string, description?: string, id?: number, title: string, url?: string }} category
 * @property {number} date
 * @property {number} id
 * @property {string} text
 * @property {string} thumbnailUrl
 * @property {string} title
 * @property {string} url
 * @property {number} views
 * @property {{ username: string }} writer
 */

/**
 * @typedef {Object} Server
 * @property {string | null} iconUrl
 * @property {number} id
 * @property {boolean} main
 * @property {number} maxPlayerCount
 * @property {string} motd
 * @property {string} name
 * @property {boolean} online
 * @property {number} playerCount
 * @property {'BUNGEECORD' | 'FABRIC' | 'FOLIA' | 'PAPER' | 'SPIGOT' | 'BUKKIT' | 'VELOCITY' | 'VANILLA' | 'PURPUR' | 'WATERFALL' | 'QUILT' | 'FORGE' | 'NEOFORGE'} type
 * @property {string} version
 */

/**
 * @typedef {Object} Session
 * @property {string} [csrfToken]
 * @property {number} [expiresAt]
 * @property {string} [sessionToken]
 */

/**
 * @typedef {Object} Ticket
 * @property {{ color?: string, description?: string, id?: number, title: string, url?: string }} category
 * @property {number} date
 * @property {number} id
 * @property {number} lastUpdate
 * @property {'NEW' | 'REPLIED' | 'CLOSED'} status
 * @property {string} title
 * @property {{ username: string | null }} writer
 */

/**
 * @typedef {Object} TicketCategory
 * @property {string} description
 * @property {number} id
 * @property {string} title
 * @property {string} url
 */

/**
 * @typedef {Object} TicketDetail
 * @property {{ title: string, url: string }} category
 * @property {number} date
 * @property {number} id
 * @property {number} messageCount
 * @property {TicketMessage[]} messages
 * @property {'NEW' | 'REPLIED' | 'CLOSED'} status
 * @property {string} title
 * @property {string} username
 */

/**
 * @typedef {Object} TicketMessage
 * @property {number} date
 * @property {number} id
 * @property {string} message
 * @property {number} panel
 * @property {number} ticketId
 * @property {number} userId
 * @property {string} username
 */

/**
 * @typedef {Object} User
 * @property {number} [lastLoginDate]
 * @property {number} registerDate
 */

/** @typedef {Record<string, any>} ChangeEmailResponse */

/**
 * @typedef {Object} ChangeEmailRequest
 * @property {string} currentPassword
 * @property {string} newEmail
 */

/** @typedef {Session} CompletePendingAuthResponse */

/**
 * @typedef {Object} CompletePendingAuthRequest
 * @property {string} pendingToken
 */

/** @typedef {{ id: number }} CreateTicketResponse */

/**
 * @typedef {Object} CreateTicketRequest
 * @property {number} categoryId
 * @property {string} message
 * @property {string} title
 */

/** @typedef {{ expiresIn: number, ticket: string }} CreateWsTicketResponse */

/** @typedef {Record<string, any>} DeleteAllNotificationResponse */

/** @typedef {Record<string, any>} DeleteNotificationResponse */

/** @typedef {{ admin: boolean, email: string | null, panelAccess: boolean, permissions: string[], username: string }} GetCredentialsResponse */

/** @typedef {Record<string, any>} GetCsrfTokenResponse */

/** @typedef {Blob} GetFaviconResponse */

/** @typedef {{ files: Record<string, any>, id: string, settings: Record<string, any> }} GetFrontendSettingsResponse */

/** @typedef {{ siteUrl: string, urls: Record<string, string> }} GetFrontendUrlsResponse */

/** @typedef {{ items: Locale[] }} GetLocalesResponse */

/** @typedef {{ notifications: Notification[] }} GetMoreNotificationsResponse */

/** @typedef {{ sessions: { expireDate: number, id: number, ip: string, isCurrent: boolean, lastActivityTime: number, userAgent: string }[] }} GetMySessionsResponse */

/** @typedef {{ items: Notification[], page: Page }} GetNotificationsResponse */

/** @typedef {{ components: Record<string, any>, info: Record<string, any>, openapi: string, paths: Record<string, any>, servers: any[] }} GetOpenApiResponse */

/** @typedef {User} GetPlayerProfileResponse */

/** @typedef {{ components: Record<string, any>, info: Record<string, any>, openapi: string, paths: Record<string, any>, servers: any[] }} GetPluginOpenApiResponse */

/** @typedef {{ plugins: Record<string, Record<string, any>> }} GetPluginPackagesResponse */

/** @typedef {{ locale: string, translations: Record<string, any> }} GetPluginTranslationsResponse */

/** @typedef {Blob} GetPluginUiFileResponse */

/** @typedef {PostDetail} GetPostDetailResponse */

/** @typedef {PostDetail} GetPostPreviewResponse */

/** @typedef {Blob} GetPostThumbnailResponse */

/** @typedef {{ items: PostSummary[], page: Page }} GetPostsResponse */

/** @typedef {User} GetProfileResponse */

/** @typedef {Blob} GetProfilePictureResponse */

/** @typedef {{ notificationCount: number, notifications: Notification[] }} GetQuickNotificationsResponse */

/** @typedef {{ registerAgreement: string }} GetRegisterAgreementResponse */

/** @typedef {{ address: string, items: Server[] }} GetServersResponse */

/** @typedef {{ allowUserLocaleSelection: boolean, developmentMode: boolean, emailEnabled: boolean, faviconHash: string, hasRegisterAgreement: boolean, homePage: string | null, ipAddress: string, isDemo: boolean, keywords: string[], locale: string, locales?: Locale[], panoVersion: string, platformLocale: string, plugins: Record<string, { dependencies: string[], uiHash: string, version: string | null }>, supportEmail: string, themeSettings: Record<string, any>, usageMode: 'WEBSITE' | 'SERVERS' | 'BOTH', userLocaleCode?: string | null, websiteDescription: string, websiteLogoHash: string, websiteName: string, websiteUrl: string }} GetSiteInfoResponse */

/** @typedef {{ items: { params: Record<string, any>, type: string, updatedAt?: number }[], page: Page }} GetSitemapResponse */

/** @typedef {Blob} GetThemeSettingResourceResponse */

/** @typedef {{ ticket: TicketDetail }} GetTicketResponse */

/** @typedef {{ items: TicketCategory[], page: Page }} GetTicketCategoriesResponse */

/** @typedef {{ messages: TicketMessage[] }} GetTicketMessagesResponse */

/** @typedef {{ items: Ticket[], page: Page }} GetTicketsResponse */

/** @typedef {{ data: Record<string, any>, meta: { pluginAdminKeys: Record<string, any>, totalCount: number } }} GetTranslationsResponse */

/** @typedef {Blob} GetWebsiteLogoResponse */

/** @typedef {any} GetWidgetIndexResponse */

/** @typedef {any} GetWidgetLoaderResponse */

/** @typedef {any} GetWidgetRuntimeFileResponse */

/** @typedef {any} HealthResponse */

/** @typedef {{ ipAddress: string, lastRegisteredUsers: { lastActivityTime: number, registerDate: number, username: string }[], mainServer: { maxPlayerCount: number, playerCount: number, status: 'ONLINE' | 'OFFLINE' } | null, serverGameVersion: string }} HomeSidebarResponse */

/** @typedef {Session} LoginResponse */

/**
 * @typedef {Object} LoginRequest
 * @property {string} [newUsername]
 * @property {boolean} [panel]
 * @property {string} [password]
 * @property {string} [registerEmail]
 * @property {string} usernameOrEmail
 */

/** @typedef {Record<string, any>} LogoutResponse */

/** @typedef {Record<string, any>} LogoutMySessionResponse */

/** @typedef {Record<string, any>} MarkNotificationAsReadResponse */

/** @typedef {{ notificationCount: number }} MarkQuickNotificationsAsReadResponse */

/** @typedef {{ banned: boolean, inGame: boolean, lastActivityTime: number, permissionGroupName: string | null }} PlayerProfileSidebarResponse */

/** @typedef {{ inGame: boolean, lastActivityTime: number, permissionGroupName: string | null }} ProfileSidebarResponse */

/** @typedef {{ csrfToken?: string, email?: string, emailVerificationRequired?: boolean, expiresAt?: number, login?: boolean, sessionToken?: string }} RegisterResponse */

/**
 * @typedef {Object} RegisterRequest
 * @property {boolean} agreement
 * @property {string} email
 * @property {string} password
 * @property {string} passwordRepeat
 * @property {string} [registerWithLinkToken]
 * @property {string} [username]
 */

/** @typedef {Record<string, any>} RenewPasswordResponse */

/**
 * @typedef {Object} RenewPasswordRequest
 * @property {string} [captchaToken]
 * @property {string} newPassword
 * @property {string} newPasswordRepeat
 * @property {string} token
 */

/** @typedef {Record<string, any>} ResetPasswordResponse */

/**
 * @typedef {Object} ResetPasswordRequest
 * @property {string} [captchaToken]
 * @property {string} usernameOrEmail
 */

/** @typedef {Record<string, any>} SendResetPasswordEmailResponse */

/** @typedef {{ message: TicketMessage }} SendTicketMessageResponse */

/**
 * @typedef {Object} SendTicketMessageRequest
 * @property {string} message
 */

/** @typedef {{ items: string[] }} SupportSidebarResponse */

/** @typedef {{ counted: boolean }} TrackPostViewResponse */

/** @typedef {Record<string, any>} UpdateProfileResponse */

/**
 * @typedef {Object} UpdateProfileRequest
 * @property {string} [localeCode]
 */

/** @typedef {Record<string, any>} UpdateTicketResponse */

/**
 * @typedef {Object} UpdateTicketRequest
 * @property {'NEW' | 'REPLIED' | 'CLOSED'} [status]
 */

/** @typedef {Record<string, any>} VerifyEmailResponse */

/**
 * @typedef {Object} VerifyEmailRequest
 * @property {string} [captchaToken]
 * @property {string} token
 */

/** @typedef {{ token: string, username: string }} VerifyLinkCodeResponse */

/**
 * @typedef {Object} VerifyLinkCodeRequest
 * @property {string} [captchaToken]
 * @property {string} code
 * @property {string} username
 */

/** @typedef {Record<string, any>} VerifyNewEmailResponse */

/**
 * @typedef {Object} VerifyNewEmailRequest
 * @property {string} [captchaToken]
 * @property {string} token
 */

/** @typedef {Record<string, any>} VisitorVisitResponse */

/** @typedef {any} WebsiteWebSocketResponse */

export {};
