import { describe, expect, test } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { basename, join, relative, resolve } from "node:path";
import postcss from "postcss";

import { checkStyles } from "../../../../plugin-kit/src/styles/check-styles.js";
import { addPartClasses, addRootClass, rootClassOf } from "../../../../plugin-kit/src/styles/semantic-classes.js";
import { ENGINE_SAFELIST, OUTPUTS, ROOT, build, scanEngine } from "../../../../../scripts/build-tokens.js";
import { baseClassSet } from "../../../../plugin-kit/src/styles/fallback-css.js";

// TC-57: the engine's own markup follows the semantic-class convention of doc 03 section 1 with
// ns = "pano" (`pano-post`, `pano-post__title`), committed as source (no build-time preprocessor for
// the engine), and the engine has its own scoped fallback sheet, generated by scripts/build-tokens.js.

const pkg = resolve(import.meta.dir, "..", "..", "..");
const lib = join(pkg, "src", "lib");
const NS = "pano";

/** Engine views: every file the generated view table points at, plus every .svelte under lib/views. */
function engineFiles() {
  const files = new Set();
  const table = readFileSync(join(lib, "views", "parts", "engine-views.generated.js"), "utf-8");
  for (const m of table.matchAll(/import\("([^"]+\.svelte)"\)/g)) files.add(resolve(lib, "views", "parts", m[1]));
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".svelte")) files.add(full);
    }
  };
  walk(join(lib, "views"));
  return [...files].sort();
}

const files = engineFiles();
const rel = (file) => relative(pkg, file).split("\\").join("/");
const views = files.map((file) => ({ name: basename(file, ".svelte"), file: rel(file) }));
const inScope = new Set(views.map((v) => v.file));

describe("engine semantic classes (doc 03 section 1, ns = pano)", () => {
  test("covers 57 engine files: the views, their parts and the registry components", () => {
    expect(files.length).toBe(57);
    for (const name of ["HomeView", "LoginView", "Post", "Navbar", "Footer", "RegisterForm", "Pagination", "Toast"]) {
      expect(views.some((v) => v.name === name)).toBe(true);
    }
  });

  test("`pano-plugin classes --fix` with ns pano has nothing left to write", () => {
    const missing = [];
    for (const file of files) {
      const view = basename(file, ".svelte");
      const source = readFileSync(file, "utf-8");
      const root = addRootClass(source, { ns: NS, view });
      const parts = addPartClasses(root.code, { ns: NS, view });
      for (const name of [...root.added, ...parts.added.map((a) => a.class)]) missing.push(`${rel(file)}: ${name}`);
    }
    expect(missing).toEqual([]);
  });

  test("a root element carries the view's root class in source", () => {
    expect(rootClassOf(NS, "ProfileView")).toBe("pano-profile-view");
    expect(readFileSync(join(lib, "views", "ProfileView.svelte"), "utf-8")).toContain("pano-profile-view");
    expect(readFileSync(join(lib, "views", "parts", "Post.svelte"), "utf-8")).toMatch(/pano-post[ '"]/);
    expect(readFileSync(join(lib, "views", "parts", "Post.svelte"), "utf-8")).toContain("pano-post__title");
  });

  test("existing class names stay: Bootstrap classes are still beside the semantic ones", () => {
    const source = readFileSync(join(lib, "views", "parts", "TicketStatus.svelte"), "utf-8");
    expect(source).toContain("pano-ticket-status pano-ticket-status__badge badge text-bg-success rounded-pill");
  });
});

/**
 * What the engine does not pass yet, per file and rule. These findings exist today and the work order
 * keeps the default render pixel-identical with the existing class names, so they stay: the `<style>`
 * blocks, the engine's own classes (`post-detail-cover`, `demo-bubble`), inline styles built from theme
 * settings and `var(--bs-*)` inside `<style>`. The list may shrink (a view moved to semantic classes and
 * `--pano-*`), never grow: a new finding fails the test.
 */
const KNOWN_BADGE_DEBT = {
  "components/Footer.svelte|style-block-scope": 1,
  "components/Footer.svelte|class-allowed": 2,
  "components/Footer.svelte|dynamic-class": 1,
  "components/Footer.svelte|style-attr": 1,
  "components/Header.svelte|class-allowed": 3,
  "components/Header.svelte|style-attr": 3,
  "components/Header.svelte|dynamic-class": 2,
  "components/LoginFormBody.svelte|style-block-scope": 2,
  "components/Navbar.svelte|style-block-scope": 10,
  "components/Navbar.svelte|class-allowed": 14,
  "components/Navbar.svelte|dynamic-class": 2,
  "components/Navbar.svelte|style-attr": 1,
  "components/PageActions.svelte|style-block-scope": 1,
  "components/PageActions.svelte|class-allowed": 3,
  "components/PageActions.svelte|dynamic-class": 3,
  "components/PageTitle.svelte|class-allowed": 3,
  "components/RegisterForm.svelte|style-block-scope": 2,
  "views/ActivateEmailView.svelte|class-allowed": 1,
  "views/AuthLayoutView.svelte|style-block-scope": 1,
  "views/ConfirmNewEmailView.svelte|class-allowed": 1,
  "views/CreateTicketView.svelte|style-block-scope": 2,
  "views/LoginView.svelte|style-block-scope": 4,
  "views/LoginView.svelte|no-bs-var": 2,
  "views/LoginView.svelte|class-allowed": 2,
  "views/MainLayoutView.svelte|class-allowed": 1,
  "views/MainLayoutView.svelte|dynamic-class": 1,
  "views/NotificationsView.svelte|class-allowed": 4,
  "views/NotificationsView.svelte|dynamic-class": 1,
  "views/parts/Breadcrumb.svelte|dynamic-class": 2,
  "views/parts/Breadcrumb.svelte|style-block-scope": 2,
  "views/parts/NotificationContainer.svelte|dynamic-class": 1,
  "views/parts/NotificationContainer.svelte|class-allowed": 1,
  "views/parts/HomeSidebar.svelte|class-allowed": 6,
  "views/parts/HomeSidebar.svelte|dynamic-class": 6,
  "views/parts/HomeSidebar.svelte|style-attr": 4,
  "views/parts/HomeSidebar.svelte|style-block-scope": 5,
  "views/parts/PlayerDetailSidebar.svelte|class-allowed": 1,
  "views/parts/PlayerDetailSidebar.svelte|style-block-scope": 3,
  "views/parts/ProfileSidebar.svelte|class-allowed": 1,
  "views/parts/ProfileSidebar.svelte|style-block-scope": 3,
  "views/parts/Post.svelte|style-block-scope": 10,
  "views/parts/Post.svelte|no-bs-var": 10,
  "views/parts/Post.svelte|class-allowed": 9,
  "views/parts/Sidebar.svelte|class-allowed": 2,
  "views/parts/TicketRow.svelte|style-attr": 1,
  "views/parts/Toast.svelte|class-allowed": 2,
  "views/parts/Toast.svelte|dynamic-class": 1,
  "views/PostDetailView.svelte|style-block-scope": 4,
  "views/PostDetailView.svelte|class-allowed": 5,
  "views/PreviewPostView.svelte|style-block-scope": 4,
  "views/PreviewPostView.svelte|class-allowed": 3,
  "views/RegisterView.svelte|class-allowed": 1,
  "views/RegisterView.svelte|style-block-scope": 2,
  "views/RegisterView.svelte|no-bs-var": 2,
  "views/SettingsView.svelte|class-allowed": 4,
  "views/SupportView.svelte|class-allowed": 1,
  "views/SupportView.svelte|style-block-scope": 1,
  "views/ThemeSettingsView.svelte|class-allowed": 19,
  "views/ThemeSettingsView.svelte|style-attr": 11,
  "views/ThemeSettingsView.svelte|style-block-scope": 3,
  "views/ThemeSettingsView.svelte|no-bs-var": 3,
  "views/TicketDetailView.svelte|class-allowed": 5,
  "views/TicketDetailView.svelte|style-block-scope": 3,
};

/** Views whose top level is a component, so there is no element to carry the root class (doc 03 section 1.2). */
const NO_ROOT_ELEMENT = [
  "views/AppLayoutView.svelte",
  "views/ProfileLayoutView.svelte",
  "views/TicketsLayoutView.svelte",
  "views/parts/DefaultToast.svelte",
  "views/parts/HomeSidebar.svelte",
  "views/parts/PlayerDetailSidebar.svelte",
  "views/parts/ProfileSidebar.svelte",
  "views/parts/SupportSidebar.svelte",
  "views/parts/TicketCreateAndDetailSidebar.svelte",
];

describe("engine style lint at badge level (checkStyles)", () => {
  const findings = checkStyles({ root: pkg, ns: NS, viewsDir: "src/lib", views, level: "badge" }).filter((f) => inScope.has(f.file));
  const where = (f) => `${f.file}:${f.line} ${f.rule}: ${f.message}`;

  test("the rules the semantic-class codemod answers are clean: root-class, part-coverage, part-prefix", () => {
    const errors = findings.filter((f) => ["root-class", "part-coverage", "part-prefix"].includes(f.rule) && f.level === "error");
    expect(errors.map(where)).toEqual([]);
  });

  test("the only views without a root class have no element root, and say so as a warning", () => {
    const roots = findings.filter((f) => f.rule === "root-class");
    expect(roots.every((f) => f.level === "warn")).toBe(true);
    expect(roots.map((f) => f.file).sort()).toEqual(NO_ROOT_ELEMENT.map((f) => `src/lib/${f}`).sort());
  });

  test("no finding beyond the known debt (class-allowed, style-block-scope, style-attr, no-bs-var, dynamic-class)", () => {
    const counts = {};
    for (const f of findings) {
      if (["root-class", "part-coverage", "part-prefix"].includes(f.rule)) continue;
      const key = `${f.file.replace("src/lib/", "")}|${f.rule}`;
      counts[key] = (counts[key] ?? 0) + 1;
    }
    const grown = Object.entries(counts)
      .filter(([key, n]) => n > (KNOWN_BADGE_DEBT[key] ?? 0))
      .map(([key, n]) => `${key}: ${n} (allowed ${KNOWN_BADGE_DEBT[key] ?? 0})`);
    expect(grown).toEqual([]);
  });

  test("the known-debt list names real findings only (drop an entry once its view is clean)", () => {
    const seen = new Set(findings.map((f) => `${f.file.replace("src/lib/", "")}|${f.rule}`));
    expect(Object.keys(KNOWN_BADGE_DEBT).filter((key) => !seen.has(key))).toEqual([]);
  });
});

describe("engine fallback sheet (assets/css/pano-fallback.css)", () => {
  const committed = readFileSync(join(ROOT, OUTPUTS.fallback), "utf-8");

  test("is generated at the path the engine links", () => {
    expect(OUTPUTS.fallback).toBe("packages/theme-core/assets/css/pano-fallback.css");
  });

  test("regenerating gives the committed file (drift)", () => {
    expect(build()[OUTPUTS.fallback]).toBe(committed);
  });

  test("is scoped to the pano namespace, layered, and has no !important", () => {
    expect(committed).toContain('@scope (.pano-fb[data-pano-fb="pano"]) to (.pano-fb-stop,');
    expect(committed).toContain("@layer pano-defaults, pano-fallback.components, pano-fallback.utilities, pano-plugin;");
    expect(committed).not.toContain("!important");
  });

  test("holds the Bootstrap classes the engine views use and the classes it builds from settings", () => {
    const base = readFileSync(join(ROOT, OUTPUTS.base), "utf-8");
    const used = scanEngine(baseClassSet(base));
    for (const c of ["navbar", "card", "btn", "form-control", "badge", "modal", "table", ...ENGINE_SAFELIST]) {
      expect(used).toContain(c);
      expect(committed).toContain(`.${c}`);
    }
    const sheet = postcss.parse(committed);
    expect(sheet.nodes.some((n) => n.type === "atrule" && n.name === "layer")).toBe(true);
  });

  test("the class list the sheet is built from is sorted and unique", () => {
    const base = readFileSync(join(ROOT, OUTPUTS.base), "utf-8");
    const used = scanEngine(baseClassSet(base));
    expect(used).toEqual([...used].sort());
    expect(new Set(used).size).toBe(used.length);
  });
});
