/**
 * Factory for a theme's vite.config.js (plain-node context). A theme's config
 * becomes:
 *
 *   import { createViteConfig } from "@panomc/theme-core/kit/vite-config";
 *   export default createViteConfig();
 *
 * Owning this file in core kills the config-drift class (blocky/frost's stale
 * vite majors, hand-edited proxy blocks, missing dedupe entries): a toolchain
 * fix ships as a core bump.
 */
import { defineConfig, loadEnv } from "vite";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { importFromTheme } from "./resolve.js";

const require = createRequire(import.meta.url);

function copyFolderPlugin(folder) {
  let outDir = "";

  return {
    name: `copy-${folder}-folder`,
    apply: "build", // Run only during build
    configResolved() {
      outDir = "build/";
    },
    async closeBundle() {
      const srcDir = path.resolve(process.cwd(), folder);
      const destDir = path.resolve(process.cwd(), outDir, folder);

      if (!fs.existsSync(srcDir)) {
        console.warn(`Source folder "${folder}" not found at: ${srcDir}`);
        return;
      }

      try {
        await fs.promises.cp(srcDir, destDir, { recursive: true });
        console.log(`Copied "${folder}" folder from ${srcDir} to ${destDir}`);
      } catch (error) {
        console.error(`Error copying "${folder}" folder:`, error);
      }
    },
  };
}

function copyManifestPlugin(filename = "manifest.json") {
  let outDir = "";

  return {
    name: "copy-manifest-json",
    apply: "build",
    configResolved() {
      outDir = "build/";
    },
    async closeBundle() {
      const srcPath = path.resolve(process.cwd(), filename);
      const destPath = path.resolve(process.cwd(), outDir, filename);

      if (!fs.existsSync(srcPath)) {
        console.warn(`Manifest file not found at: ${srcPath}`);
        return;
      }

      try {
        await fs.promises.copyFile(srcPath, destPath);
        console.log(`Copied manifest from ${srcPath} to ${destPath}`);
      } catch (err) {
        console.error("Failed to copy manifest.json:", err);
      }
    },
  };
}

function copyCoreMetaPlugin() {
  // core-meta.json is the sidecar that carries theme metadata the platform
  // must not rewrite (coreVersion, tier, baseTheme). See docs/P0-SPIKE.md §6.
  let outDir = "";

  return {
    name: "copy-core-meta-json",
    apply: "build",
    configResolved() {
      outDir = "build/";
    },
    async closeBundle() {
      const srcPath = path.resolve(process.cwd(), "core-meta.json");
      if (!fs.existsSync(srcPath)) return;

      const corePkg = require("@panomc/theme-core/package.json");
      const meta = JSON.parse(await fs.promises.readFile(srcPath, "utf-8"));
      meta.coreVersion = corePkg.version;

      const destPath = path.resolve(process.cwd(), outDir, "core-meta.json");
      await fs.promises.writeFile(destPath, JSON.stringify(meta, null, 2));
      console.log(`Wrote core-meta.json (coreVersion ${corePkg.version})`);
    },
  };
}

/** Absolute path to @panomc/theme-core's src/ inside the consumer's node_modules. */
function corePackageSrc() {
  return path.dirname(require.resolve("@panomc/theme-core/package.json")) + "/src";
}

/**
 * @param {object} [opts]
 * @param {string} [opts.base]  app base path ("" for themes, "/panel" for panel-ui);
 *   drives the extra dev proxy entry and hmr path
 * @param {string[]} [opts.copyFolders]  folders copied into build/ (default lang+screenshots;
 *   panel: ["lang"])
 * @param {object} [opts.extraAliases]  additional resolve.alias entries
 * @param {string[]} [opts.extraNoExternalDev]  extra ssr.noExternal entries for dev
 * @param {string[]} [opts.extraOptimizeExclude]  extra optimizeDeps.exclude entries
 * @param {any[]} [opts.extraPlugins]  profile-specific vite plugins appended to the list
 * @param {(config: object, ctx: {command: string}) => object} [opts.finalize]
 *   last-chance escape hatch to adjust the resolved config
 */
export function createViteConfig(opts = {}) {
  const base = opts.base ?? "";
  const copyFolders = opts.copyFolders ?? ["lang", "screenshots"];
  const env = loadEnv("", process.cwd());

  return defineConfig(async ({ command }) => {
    // The kit vite plugin MUST come from the theme's own node_modules — core's
    // copy can be a different version and would drive the build with mismatched
    // $app/runtime code (see kit/resolve.js).
    const { sveltekit } = await importFromTheme("@sveltejs/kit", "./vite");

    const config = {
      clearScreen: false,
      plugins: [
        sveltekit(),
        // NOTE: licenses.json is generated by bin/license/finalize-fingerprint.js
        // AFTER vite build — a closeBundle plugin races adapter-node's build/
        // rewrite (SSR pass's output gets wiped by the final adapter pass).
        ...copyFolders.map((f) => copyFolderPlugin(f)),
        copyManifestPlugin(),
        copyCoreMetaPlugin(),
        ...(opts.extraPlugins ?? []),
      ],
      // NOTE: The theme file-fingerprint is stamped into build/manifest.json by
      // bin/license/finalize-fingerprint.js, which the theme's `build` script runs
      // AFTER `vite build`. Doing it inside a vite plugin would race with SvelteKit's
      // adapter-node two-pass bundling (SSR + client), producing a digest that doesn't
      // cover all files.
      ssr: {
        noExternal:
          command === "build"
            ? true
            : [
                "@panomc/sdk",
                "@panomc/theme-core",
                "svelte-i18n",
                ...(opts.extraNoExternalDev ?? []),
              ],
      },
      css: {
        preprocessorOptions: {
          scss: {
            api: "modern-compiler",
            loadPaths: [
              process.cwd(),
              path.resolve(process.cwd(), "node_modules"),
            ],
            quietDeps: true,
            silenceDeprecations: [
              "mixed-decls",
              "color-functions",
              "global-builtin",
              "import",
            ],
          },
        },
      },
      optimizeDeps: {
        include: ["deepmerge", "svelte-i18n"],
        exclude: [
          "@panomc/sdk",
          "@panomc/theme-core",
          "svelte",
          ...(opts.extraOptimizeExclude ?? []),
        ],
      },
      server: {
        proxy: {
          // NEVER proxy /plugins here: the app itself serves plugin client
          // chunks; proxying it to the backend creates a request loop.
          "/api": env.VITE_API_URL
            ? env.VITE_API_URL.replace("/api", "")
            : "http://localhost:8088",
          ...(base
            ? {
                [`${base}/api`]: env.VITE_API_URL
                  ? env.VITE_API_URL.replace(`${base}/api`, "").replace("/api", "")
                  : "http://localhost:8088",
              }
            : {}),
        },
        allowedHosts: true,
        hmr: {
          path: base ? `${base}/` : "/",
        },
      },
      resolve: {
        alias: {
          // $pano resolves core-internal imports; it works in every
          // vite-processed context (theme code, core code, generated shims).
          "$pano": corePackageSrc(),
          "@theme-style":
            command === "serve" && process.env.VITE_DEV_UI !== "true"
              ? path.resolve(process.cwd(), "src/styles/_empty.scss")
              : path.resolve(process.cwd(), "src/styles/style.scss"),
          ...(opts.extraAliases ?? {}),
        },
        preserveSymlinks: true,
        // @sveltejs/kit is deduped so core-internal `import { error } from
        // "@sveltejs/kit"` resolves to the THEME's kit, not a second copy from
        // core's own node_modules.
        dedupe: [
          "svelte",
          "@panomc/sdk",
          "@panomc/theme-core",
          "svelte-i18n",
          "@sveltejs/kit",
          // core's own runtime deps: resolve them from the THEME's root so a
          // symlinked (file:/link:) core never drags in a second copy from its
          // own isolated store (preserveSymlinks defeats nested resolution).
          "date-fns",
          "copy-to-clipboard",
          "@jill64/universal-sanitizer",
          "mime-types",
          "tippy.js",
          "adm-zip",
        ],
      },
      build: {
        manifest: true,
        // svelte/@panomc/sdk/@panomc/theme-core are deliberately NOT externalized:
        // the host bundles its own runtime (immutable-cached under /_app/immutable),
        // and plugins reach the very same module instances through the /runtime
        // shims + the registry installed by kit/hooks-client.js.
      },
    };

    return opts.finalize ? opts.finalize(config, { command }) : config;
  });
}
