// The engine's sample files (`lib/views/<Name>.samples.js`), one lazy import each (doc 02 section 7).
//
// Generated from the folder, not `import.meta.glob`: the glob's transform emits relative specifiers that
// vite's dependency scanner cannot resolve when the engine is a registry install (see plugin-ui/Layout.svelte).
// A test keeps this table equal to the files on disk; regenerate it when a samples file is added.

/** @type {Record<string, () => Promise<{ default: import("./model.js").Samples, notApplicable?: string[] }>>} */
export const ENGINE_SAMPLES = {
  ActivateEmailView: () => import("../../lib/views/ActivateEmailView.samples.js"),
  AppLayoutView: () => import("../../lib/views/AppLayoutView.samples.js"),
  AuthLayoutView: () => import("../../lib/views/AuthLayoutView.samples.js"),
  Breadcrumb: () => import("../../lib/views/Breadcrumb.samples.js"),
  CloseTicketConfirmModal: () => import("../../lib/views/CloseTicketConfirmModal.samples.js"),
  ConfirmNewEmailView: () => import("../../lib/views/ConfirmNewEmailView.samples.js"),
  ConfirmRemoveAllNotificationsModal: () => import("../../lib/views/ConfirmRemoveAllNotificationsModal.samples.js"),
  CreateTicketView: () => import("../../lib/views/CreateTicketView.samples.js"),
  Date: () => import("../../lib/views/Date.samples.js"),
  DefaultToast: () => import("../../lib/views/DefaultToast.samples.js"),
  ErrorView: () => import("../../lib/views/ErrorView.samples.js"),
  Footer: () => import("../../lib/views/Footer.samples.js"),
  Header: () => import("../../lib/views/Header.samples.js"),
  HomeSidebar: () => import("../../lib/views/HomeSidebar.samples.js"),
  HomeView: () => import("../../lib/views/HomeView.samples.js"),
  LoginFormBody: () => import("../../lib/views/LoginFormBody.samples.js"),
  LoginView: () => import("../../lib/views/LoginView.samples.js"),
  LogoutSessionConfirmModal: () => import("../../lib/views/LogoutSessionConfirmModal.samples.js"),
  Main: () => import("../../lib/views/Main.samples.js"),
  Navbar: () => import("../../lib/views/Navbar.samples.js"),
  NoContent: () => import("../../lib/views/NoContent.samples.js"),
  NotificationContainer: () => import("../../lib/views/NotificationContainer.samples.js"),
  NotificationsView: () => import("../../lib/views/NotificationsView.samples.js"),
  PageActions: () => import("../../lib/views/PageActions.samples.js"),
  PageTitle: () => import("../../lib/views/PageTitle.samples.js"),
  Pagination: () => import("../../lib/views/Pagination.samples.js"),
  PlayerDetailSidebar: () => import("../../lib/views/PlayerDetailSidebar.samples.js"),
  PlayerDetailView: () => import("../../lib/views/PlayerDetailView.samples.js"),
  PlayerHead: () => import("../../lib/views/PlayerHead.samples.js"),
  Post: () => import("../../lib/views/Post.samples.js"),
  PostDetailView: () => import("../../lib/views/PostDetailView.samples.js"),
  Posts: () => import("../../lib/views/Posts.samples.js"),
  PreviewPostView: () => import("../../lib/views/PreviewPostView.samples.js"),
  ProfileLayoutView: () => import("../../lib/views/ProfileLayoutView.samples.js"),
  ProfileSidebar: () => import("../../lib/views/ProfileSidebar.samples.js"),
  ProfileView: () => import("../../lib/views/ProfileView.samples.js"),
  RegisterForm: () => import("../../lib/views/RegisterForm.samples.js"),
  RegisterView: () => import("../../lib/views/RegisterView.samples.js"),
  RenewPasswordView: () => import("../../lib/views/RenewPasswordView.samples.js"),
  ResetPasswordView: () => import("../../lib/views/ResetPasswordView.samples.js"),
  RulesView: () => import("../../lib/views/RulesView.samples.js"),
  Sidebar: () => import("../../lib/views/Sidebar.samples.js"),
  SupportSidebar: () => import("../../lib/views/SupportSidebar.samples.js"),
  SupportView: () => import("../../lib/views/SupportView.samples.js"),
  ThemeSettingsLayoutView: () => import("../../lib/views/ThemeSettingsLayoutView.samples.js"),
  TicketCreateAndDetailSidebar: () => import("../../lib/views/TicketCreateAndDetailSidebar.samples.js"),
  TicketDetailView: () => import("../../lib/views/TicketDetailView.samples.js"),
  TicketRow: () => import("../../lib/views/TicketRow.samples.js"),
  TicketStatus: () => import("../../lib/views/TicketStatus.samples.js"),
  Tickets: () => import("../../lib/views/Tickets.samples.js"),
  TicketsLayoutView: () => import("../../lib/views/TicketsLayoutView.samples.js"),
  TicketsView: () => import("../../lib/views/TicketsView.samples.js"),
  Toast: () => import("../../lib/views/Toast.samples.js"),
  ToastContainer: () => import("../../lib/views/ToastContainer.samples.js"),
};
