/**
 * @typedef {Object} CartState
 * @property {'idle' | 'busy'} status
 * @property {{ id: number }[]} lines
 * @property {number} count
 */

export {};

// ---- generated by @panomc/plugin-kit, do not edit below this line ----

/**
 * What a theme, a web component or plain JS holds. `name` is "market/cart" (namespace + "/" + spec.name).
 * `get()` is a snapshot, replaced on change and never mutated.
 * @template S, A
 * @typedef {Object} Controller
 * @property {string} name
 * @property {number} version
 * @property {() => S} get
 * @property {(run:(s:S)=>void) => (() => void)} subscribe
 * @property {A} actions
 * @property {() => void} destroy
 */

/**
 * @typedef {Object} ControllerHost
 * @property {string} baseUrl
 * @property {boolean} browser
 * @property {(r:{method?:string, path:string, query?:object, body?:any, headers?:object, blob?:boolean}) => Promise<any>} request
 *   Parsed body in doc 04's shape (non-2xx = { error: { code, ... } }). `path` is what follows "/api/v1".
 *   A network failure resolves { error: { code: 'NETWORK_ERROR' } }; request never rejects.
 * @property {() => {user:(object|null), csrfToken:(string|null)}} session
 * @property {() => (string|undefined)} locale
 * @property {(fn:(s:any)=>void) => (() => void)} onSession   first bind, login, logout; a no-op on the server
 * @property {(key:string, values?:object) => string} t        full key: "plugins.pano-plugin-market.x"
 * @property {(key:string, o?:{variant?:'success'|'danger'|'warning', values?:object}) => void} toast
 * @property {(kind:'local'|'session') => (Storage|null)} storage
 * @property {() => number} now
 * @property {(url:string, o?:{replace?:boolean}) => void} navigate
 * @property {(name:string) => boolean} feature
 * @property {(returnTo?:string) => string} loginUrl
 * @property {(returnTo?:string) => string} registerUrl
 */

/**
 * What `host.request` resolves, and what an action returns when it can fail: the parsed body, or the error envelope.
 * @template [T=object]
 * @typedef {T | { error: { code: string, message?: string, details?: object, fields?: Record<string, string> } }} ApiResult
 */

/**
 * Actions of demo/cart, generated from its action names (declare CartActions in types.js to type them).
 * @typedef {{ add: (...args: any[]) => any, setQuantity: (...args: any[]) => any, clear: (...args: any[]) => any, retry: (...args: any[]) => any }} CartActions
 */

/**
 * State of demo/format, generated from the keys of its initial state (declare FormatState in types.js to type it).
 * @typedef {{}} FormatState
 */

/**
 * Actions of demo/format, generated from its action names (declare FormatActions in types.js to type them).
 * @typedef {{ money: (...args: any[]) => any }} FormatActions
 */

/**
 * Every public controller of demo, by full name.
 * @typedef {{ 'demo/cart': Controller<CartState, CartActions>, 'demo/format': Controller<FormatState, FormatActions> }} Controllers
 */
