// OpenAPI 3.1 document -> index.js, types.js, operations.js, openapi.json (doc 06 §2.3). Pure and deterministic.
import { canonicalJson, sortKeys } from './canonical.js'
import { ClientGenError } from './errors.js'
import { collectOperations, pascal } from './operations.js'
import { isIdent, objectProperties, oneLine, propKey, quote, schemaType } from './schema.js'

const HEADER = '// Generated by pano-client from openapi.json. Do not edit; run pano-client again.\n'

/**
 * @typedef {Object} GenerateResult
 * @property {Record<string, string>} files   file name -> content: index.js, types.js, operations.js, openapi.json
 * @property {string[]} warnings
 * @property {import('./operations.js').Operation[]} operations
 */

/**
 * @param {any} input   parsed OpenAPI 3.1 document, or its JSON text
 * @returns {GenerateResult}
 */
export function generateClient(input) {
  /** @type {any} */
  let doc = input
  if (typeof input === 'string') {
    try {
      doc = JSON.parse(input)
    } catch (e) {
      throw new ClientGenError(`The OpenAPI document is not valid JSON: ${/** @type {Error} */ (e).message}`)
    }
  }
  if (!doc || typeof doc !== 'object' || typeof doc.paths !== 'object') {
    throw new ClientGenError('The input is not an OpenAPI document (no "paths" object).')
  }
  doc = sortKeys(doc)

  /** @type {string[]} */
  const warnings = []
  const warn = (/** @type {string} */ m) => warnings.push(m)
  const operations = collectOperations(doc, warn)

  // type names: components.schemas first, then the per-operation aliases
  const schemas = doc.components && typeof doc.components.schemas === 'object' && doc.components.schemas ? doc.components.schemas : {}
  /** @type {Map<string, string>} */
  const typeNames = new Map()
  const taken = new Set()
  for (const raw of Object.keys(schemas)) {
    let name = isIdent(raw) ? raw : pascal(raw) || 'Schema'
    if (/^[0-9]/.test(name)) name = '_' + name
    let unique = name
    for (let n = 2; taken.has(unique); n++) unique = `${name}${n}`
    if (unique !== name) warn(`schema "${raw}" maps to a type name that is taken, using "${unique}"`)
    taken.add(unique)
    typeNames.set(raw, unique)
  }
  const claim = (/** @type {string} */ base) => {
    let name = base
    if (taken.has(name)) name = base + 'Operation'
    for (let n = 2; taken.has(name); n++) name = `${base}Operation${n}`
    taken.add(name)
    return name
  }
  const refIn = (/** @type {boolean} */ local) => (/** @type {string} */ name) => {
    const t = typeNames.get(name)
    if (t === undefined) {
      warn(`reference to unknown schema "${name}", typed as any`)
      return 'any'
    }
    return local ? t : `import('./types.js').${t}`
  }
  const localCtx = { ref: refIn(true) }
  const importCtx = { ref: refIn(false) }

  // ---- types.js
  const typeBlocks = []
  for (const raw of [...typeNames.keys()].sort()) {
    const name = /** @type {string} */ (typeNames.get(raw))
    typeBlocks.push(typedef(name, schemas[raw], localCtx))
  }

  /** @type {Map<import('./operations.js').Operation, { response: string, request: string | null }>} */
  const opTypes = new Map()
  for (const op of operations) {
    const base = pascal(op.name)
    let response
    if (op.undocumented) response = 'any'
    else if (op.response.kind === 'json') response = schemaType(op.response.schema, localCtx)
    else if (op.response.kind === 'text') response = 'string'
    else if (op.response.kind === 'blob') response = 'Blob'
    else response = 'void'
    const responseName = claim(`${base}Response`)
    typeBlocks.push(`/** @typedef {${response}} ${responseName} */`)

    let requestName = null
    if (op.body && !op.undocumented) {
      if (op.body.kind === 'json') {
        requestName = claim(`${base}Request`)
        typeBlocks.push(typedef(requestName, op.body.schema, localCtx))
      }
    }
    opTypes.set(op, { response: responseName, request: requestName })
  }
  const typesJs = HEADER + '\n' + typeBlocks.join('\n\n') + (typeBlocks.length ? '\n\n' : '') + 'export {};\n'

  // ---- operations.js
  const opLines = operations.map(
    (op) =>
      `  ${propKey(op.name)}: { method: ${quote(op.method)}, path: ${quote(op.path)}, auth: ${quote(op.auth)}, mutation: ${op.mutation} }`
  )
  const operationsJs =
    HEADER + '\n' + `export const operations = /** @type {const} */ ({\n${opLines.join(',\n')}${opLines.length ? '\n' : ''}});\n`

  // ---- index.js
  const fnBlocks = operations.map((op) => {
    const t = /** @type {{ response: string, request: string | null }} */ (opTypes.get(op))
    const { type: paramsType, required } = paramsOf(op, t.request, importCtx)
    const lines = ['/**']
    const doc1 = oneLine(op.summary) || oneLine(op.description) || `${op.method} ${op.path}`
    lines.push(` * ${doc1}`)
    if (op.summary && op.description && oneLine(op.description) !== oneLine(op.summary)) lines.push(` * ${oneLine(op.description)}`)
    if (op.deprecated) lines.push(' * @deprecated')
    lines.push(` * @param {import('@panomc/client').PanoClient} client`)
    lines.push(` * @param {${paramsType}} ${required ? 'params' : '[params]'}`)
    lines.push(
      ` * @returns {Promise<import('@panomc/client').ApiResult<import('./types.js').${t.response}>>}`
    )
    lines.push(' */')
    lines.push(`export const ${op.name} = (client, params) => client.request(operations.${op.name}, params);`)
    return lines.join('\n')
  })
  const indexJs = HEADER + "import { operations } from './operations.js';\n\n" + fnBlocks.join('\n\n') + (fnBlocks.length ? '\n' : '')

  return {
    files: { 'index.js': indexJs, 'types.js': typesJs, 'operations.js': operationsJs, 'openapi.json': canonicalJson(doc) },
    warnings,
    operations
  }
}

/**
 * @param {import('./operations.js').Operation} op
 * @param {string | null} requestName
 * @param {import('./schema.js').TypeContext} ctx
 */
function paramsOf(op, requestName, ctx) {
  const members = []
  let required = false
  if (op.undocumented) {
    if (/\{[^}]+\}/.test(op.path)) {
      members.push('path: Record<string, string | number | boolean>')
      required = true
    }
    members.push('query?: Record<string, any>')
    if (op.mutation) members.push('body?: any')
  } else {
    const pathParams = op.parameters.filter((p) => p.in === 'path')
    const queryParams = op.parameters.filter((p) => p.in === 'query')
    if (pathParams.length) {
      members.push(`path: { ${pathParams.map((p) => `${propKey(p.name)}: ${schemaType(p.schema, ctx)}`).join(', ')} }`)
      required = true
    }
    if (queryParams.length) {
      const anyRequired = queryParams.some((p) => p.required)
      members.push(
        `query${anyRequired ? '' : '?'}: { ${queryParams.map((p) => `${propKey(p.name)}${p.required ? '' : '?'}: ${schemaType(p.schema, ctx)}`).join(', ')} }`
      )
      if (anyRequired) required = true
    }
    if (op.body) {
      const type =
        op.body.kind === 'form' ? 'FormData' : op.body.kind === 'json' && requestName ? `import('./types.js').${requestName}` : 'any'
      members.push(`body${op.body.required ? '' : '?'}: ${type}`)
      if (op.body.required) required = true
    }
  }
  members.push('signal?: AbortSignal')
  return { type: `{ ${members.join(', ')} }`, required }
}

/**
 * @param {string} name
 * @param {any} schema
 * @param {import('./schema.js').TypeContext} ctx
 */
function typedef(name, schema, ctx) {
  const props = objectProperties(schema, ctx)
  const description = schema && typeof schema === 'object' ? oneLine(schema.description) : ''
  const deprecated = schema && typeof schema === 'object' && schema.deprecated === true
  if (props) {
    const lines = ['/**']
    if (description) lines.push(` * ${description}`)
    if (deprecated) lines.push(' * @deprecated')
    lines.push(` * @typedef {Object} ${name}`)
    for (const p of props) {
      lines.push(` * @property {${p.type}} ${p.optional ? `[${p.name}]` : p.name}${p.description ? ` ${p.description}` : ''}`)
    }
    lines.push(' */')
    return lines.join('\n')
  }
  const type = schemaType(schema, ctx)
  if (!description && !deprecated) return `/** @typedef {${type}} ${name} */`
  return ['/**', ...(description ? [` * ${description}`] : []), ...(deprecated ? [' * @deprecated'] : []), ` * @typedef {${type}} ${name}`, ' */'].join('\n')
}
