#!/usr/bin/env node
/**
 * Generates the committed style files that come from the `--pano-*` token table
 * (design doc 03 section 2 and 4.2):
 *
 *   packages/sdk/core/scss/_pano-tokens.scss      the bridge: `--pano-*` mirror the `--bs-*` variables
 *   packages/sdk/core/css/pano-tokens.css         literal defaults, one block per palette, in a layer
 *   packages/plugin-kit/assets/pano-bootstrap.css main.scss compiled with $pano-literal-colours: false
 *   packages/theme-core/assets/css/pano-fallback.css  the engine's own scoped fallback sheet: buildFallbackCss over
 *                                                 packages/theme-core/src/lib with ns "pano" (doc 03 section 4.2)
 *   packages/theme-core/assets/css/pano-fallback-legacy.css  the whole Bootstrap base scoped to
 *                                                 `.pano-fb[data-pano-fb="legacy"]`: what a plugin that is not on the
 *                                                 new model (no `styles.fallback`) gets in a Bootstrap-free theme
 *
 * Usage: `bun scripts/build-tokens.js` writes them, `bun scripts/build-tokens.js --check` exits 1 when
 * a committed file is out of date. `__tests__/build-tokens.test.js` runs the same check.
 */
import { cpSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as sass from "sass";
import postcss from "postcss";
import { TOKENS, PALETTES } from "../packages/plugin-kit/src/styles/tokens.map.js";
import { baseClassSet, buildFallbackCss, scanViews } from "../packages/plugin-kit/src/styles/fallback-css.js";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SCSS_DIR = join(ROOT, "packages/sdk/core/scss");

/** Generated files, relative to the repo root. */
export const OUTPUTS = {
  bridge: "packages/sdk/core/scss/_pano-tokens.scss",
  literals: "packages/sdk/core/css/pano-tokens.css",
  base: "packages/plugin-kit/assets/pano-bootstrap.css",
  fallback: "packages/theme-core/assets/css/pano-fallback.css",
  fallbackLegacy: "packages/theme-core/assets/css/pano-fallback-legacy.css",
};

/** The engine sources the fallback sheet is built from, relative to the repo root. */
export const ENGINE_LIB = "packages/theme-core/src/lib";

/**
 * Classes the engine builds at run time from a theme setting, which no scan can see:
 * `rounded-{navRoundLevel}` (Navbar) and `gap-{headerNavBarGap}` (MainLayoutView), both a 0-5 range input.
 */
export const ENGINE_SAFELIST = [0, 1, 2, 3, 4, 5].flatMap((n) => [`rounded-${n}`, `gap-${n}`]);

const HEADER = "Generated by scripts/build-tokens.js from packages/plugin-kit/src/styles/tokens.map.js. Do not edit.";

/** @param {import("../packages/plugin-kit/src/styles/tokens.map.js").PanoToken} t */
function bridgeValue(t) {
  return t.bs ? `var(${t.bs})` : `#{${t.sass}}`;
}

/** The Sass bridge: `--pano-*` declared next to (and from) the Bootstrap variables. */
export function renderBridge() {
  const line = (t) => `    ${t.token}: ${bridgeValue(t)};`;
  const normal = TOKENS.filter((t) => !t.low).map(line).join("\n");
  const low = TOKENS.filter((t) => t.low).map(line).join("\n");
  return `// ${HEADER}
//
// Imported last by core/scss/main.scss; a theme that imports Bootstrap on its own imports this file
// after Bootstrap and its tokens (@import "node_modules/@panomc/sdk/core/scss/pano-tokens";).
// Skipped when $pano-literal-colours is false: the Bootstrap base sheet carries no --pano-* variable.
$pano-literal-colours: true !default;

@if $pano-literal-colours {
  /* pano-tokens: bridge */
  :root,
  [data-bs-theme] {
${normal}
  }

  // Zero specificity, so the on-* values that define-theme sets in a palette block win.
  :where(:root, [data-bs-theme]) {
${low}
  }
}
`;
}

/**
 * Compile `core/scss/main.scss` exactly the way a theme with an empty tokens.scss does.
 * @param {{ head?: string, scssDir?: string, loadPaths?: string[], bridge?: string }} [opts]
 *   head = Sass prepended to the source, scssDir = folder holding main.scss (default: the working
 *   tree), bridge = contents of `pano-tokens` (default: freshly rendered)
 */
export function compileMain({ head = "", scssDir = SCSS_DIR, loadPaths = [ROOT], bridge } = {}) {
  /** @type {import("sass").Importer<"sync">[]} */
  const importers = [];
  if (bridge !== undefined || scssDir === SCSS_DIR) {
    const contents = bridge ?? renderBridge();
    importers.push({
      canonicalize: (url) => (url === "pano-tokens" ? new URL("pano-tokens:bridge") : null),
      load: () => ({ contents, syntax: "scss" }),
    });
  }
  const result = sass.compileString(`${head}@import "main";\n`, {
    url: pathToFileURL(join(ROOT, "tokens-entry.scss")),
    loadPaths: [scssDir, ...loadPaths],
    importers,
    logger: sass.Logger.silent,
    quietDeps: true,
    silenceDeprecations: ["import", "global-builtin", "color-functions", "mixed-decls", "if-function"],
  });
  return result.css;
}

// ----- literal defaults: resolve the cascade of the compiled sheet per palette -----

/**
 * Which palettes a selector applies to, and with what specificity (0 inside :where, else 1).
 * @param {string} selector one comma-separated selector list
 * @returns {{ spec: number, palettes: Set<string> } | null}
 */
function matchSelector(selector) {
  let spec = 1;
  const palettes = new Set();
  for (const part of selector.split(/,(?![^(]*\))/).map((s) => s.trim())) {
    const where = /^:where\((.*)\)$/.exec(part);
    if (where) {
      const inner = matchSelector(where[1]);
      if (inner) {
        spec = 0;
        inner.palettes.forEach((p) => palettes.add(p));
      }
      continue;
    }
    if (part === ":root" || part === "[data-bs-theme]") {
      PALETTES.forEach((p) => palettes.add(p));
    } else {
      const m = /^\[data-bs-theme=["']?([a-z]+)["']?\]$/.exec(part);
      if (m) palettes.add(m[1]);
    }
  }
  return palettes.size ? { spec, palettes } : null;
}

/** @param {string} value @param {Map<string,string>} vars */
function resolveVars(value, vars, depth = 0) {
  if (depth > 20) throw new Error(`variable cycle while resolving "${value}"`);
  return value.replace(/var\(\s*(--[\w-]+)\s*(?:,\s*([^()]*))?\)/g, (_, name, fallback) => {
    const found = vars.get(name);
    if (found === undefined) {
      if (fallback !== undefined) return fallback.trim();
      throw new Error(`unresolved ${name} in "${value}"`);
    }
    return resolveVars(found, vars, depth + 1);
  });
}

/**
 * The literal value of every token, per palette, from the compiled stylesheet.
 * @param {string} css compiled main.scss (bridge included)
 * @returns {Record<string, Record<string, string>>} palette -> token -> value
 */
export function resolvePalettes(css) {
  const root = postcss.parse(css);
  /** @type {{ spec: number, order: number, palettes: Set<string>, decls: [string,string][] }[]} */
  const rules = [];
  let order = 0;
  root.each((node) => {
    if (node.type !== "rule") return;
    const m = matchSelector(node.selector);
    if (!m) return;
    const decls = [];
    node.each((d) => {
      if (d.type === "decl" && d.prop.startsWith("--")) decls.push([d.prop, d.value]);
    });
    if (decls.length) rules.push({ ...m, order: order++, decls });
  });
  rules.sort((a, b) => a.spec - b.spec || a.order - b.order);

  /** @type {Record<string, Record<string, string>>} */
  const out = {};
  for (const palette of PALETTES) {
    const vars = new Map();
    for (const r of rules) if (r.palettes.has(palette)) for (const [k, v] of r.decls) vars.set(k, v);
    out[palette] = {};
    for (const t of TOKENS) {
      const raw = vars.get(t.token);
      if (raw === undefined) throw new Error(`${t.token} is not declared for palette ${palette}`);
      out[palette][t.token] = resolveVars(raw, vars).replace(/\s+/g, " ").trim();
    }
  }
  return out;
}

const PALETTE_SELECTOR = (p) => (p === "light" ? ":root,\n  [data-bs-theme='light']" : `[data-bs-theme='${p}']`);

/** `sdk/core/css/pano-tokens.css`: literal values, one block per palette, in `@layer pano-defaults`. */
export function renderLiterals(css) {
  const palettes = resolvePalettes(css);
  const blocks = PALETTES.map((p) => {
    const body = TOKENS.map((t) => `    ${t.token}: ${palettes[p][t.token]};`).join("\n");
    return `  ${PALETTE_SELECTOR(p)} {\n${body}\n  }`;
  });
  return `/* ${HEADER} */\n@layer pano-defaults {\n${blocks.join("\n\n")}\n}\n`;
}

/**
 * The classes the engine's own views use (doc 03 section 4.2, step 1), read with the same scanner a plugin
 * build uses. Tests, sample data and the catalogue files are not part of what renders, so they are staged
 * out: the scanner reads a folder, and a literal in a test must not change the committed sheet.
 *
 * @param {Set<string>} baseClasses
 * @returns {string[]} sorted
 */
export function scanEngine(baseClasses) {
  const lib = join(ROOT, ENGINE_LIB);
  const stage = mkdtempSync(join(tmpdir(), "pano-engine-scan-"));
  try {
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
          if (entry.name !== "__tests__" && entry.name !== "node_modules") walk(full);
        } else if (/\.(?:svelte|js|mjs)$/.test(entry.name) && !/\.(?:samples|test)\.m?js$/.test(entry.name)) {
          const to = join(stage, relative(lib, full));
          mkdirSync(dirname(to), { recursive: true });
          cpSync(full, to);
        }
      }
    };
    walk(lib);

    const missing = ENGINE_SAFELIST.filter((c) => !baseClasses.has(c));
    if (missing.length) throw new Error(`ENGINE_SAFELIST names classes that are not in the Bootstrap base sheet: ${missing.join(", ")}`);

    const scan = scanViews(stage, baseClasses, "pano");
    return [...new Set([...scan.used, ...ENGINE_SAFELIST])].sort();
  } finally {
    rmSync(stage, { recursive: true, force: true });
  }
}

/** `packages/theme-core/assets/css/pano-fallback.css`: the scoped fallback sheet of the engine's own views, ns `pano`. */
export function renderEngineFallback(baseCss) {
  const used = scanEngine(baseClassSet(baseCss));
  return `/* ${HEADER} */\n${buildFallbackCss({ baseCss, usedClasses: used, ns: "pano" }).css}`;
}

/**
 * `packages/theme-core/assets/css/pano-fallback-legacy.css`: the whole Bootstrap base (every class in it counts as used),
 * scoped to `.pano-fb[data-pano-fb="legacy"]` and bound to the `--pano-*` tokens. Injected views of a plugin that is not
 * on the new model (a banner, a nav item, a hook) render inside this scope in a theme with `provides.bootstrap: false`.
 */
export function renderLegacyFallback(baseCss) {
  return `/* ${HEADER} */\n${buildFallbackCss({ baseCss, usedClasses: baseClassSet(baseCss), ns: "legacy" }).css}`;
}

/** Everything the script generates, as `{ relative path: contents }`. Pure: reads the working tree only. */
export function build() {
  const bridge = renderBridge();
  const main = compileMain({ bridge });
  const base = compileMain({ bridge, head: "$pano-literal-colours: false;\n" });
  const baseSheet = `/* ${HEADER} */\n${base}`;
  return {
    [OUTPUTS.bridge]: bridge,
    [OUTPUTS.literals]: renderLiterals(main),
    [OUTPUTS.base]: baseSheet,
    [OUTPUTS.fallback]: renderEngineFallback(baseSheet),
    [OUTPUTS.fallbackLegacy]: renderLegacyFallback(baseSheet),
  };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [file, contents] of Object.entries(build())) {
    const path = join(ROOT, file);
    let current = null;
    try {
      current = readFileSync(path, "utf-8");
    } catch {}
    if (current === contents) continue;
    if (check) {
      console.error(`out of date: ${file}`);
      stale++;
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, contents);
      console.log(`wrote ${file}`);
    }
  }
  if (stale) {
    console.error("run: bun scripts/build-tokens.js");
    process.exit(1);
  }
}
